openapi: 3.0.0
servers:
  - url: http://localhost:8080/api/2.1/unity-catalog
    description: Localhost reference server
tags:
  - name: Users
    description: |
      A catalog is the first layer of Unity Catalog’s three-level namespace. It’s used to organize your data assets.
paths:
  /scim2/users:
    post:
      tags:
        - Users
      operationId: createUser
      summary: Create a user
      description: |
        Creates a new user.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './all.yaml#/components/schemas/UserResource'
      responses:
        '200':
          description: The new user was successfully created.
          content:
            application/json:
              schema:
                $ref: './all.yaml#/components/schemas/User'
    get:
      tags:
        - Users
      parameters:
        - name: filter
          in: query
          description: Query by which the results have to be filtered.
          schema:
            type: string
          required: false
        - name: startIndex
          in: query
          description: Specifies the index of the first result. First item is number 1.
          schema:
            type: integer
            format: int32
          required: false
        - name: count
          in: query
          description: Desired number of results per page.
          schema:
            type: integer
            format: int32
          required: false
      operationId: listUsers
      summary: List users
      description: |
        Gets details for all the users.
      responses:
        '200':
          description: The user list was successfully retrieved.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './all.yaml#/components/schemas/UserResource'
  /scim2/users/{id}:
    parameters:
      - name: id
        in: path
        description: The id of the user.
        required: true
        schema:
          type: string
    get:
      tags:
        - Users
      operationId: getUser
      summary: Get a user
      description: |
        Gets the specified user.
      responses:
        '200':
          description: The user was successfully retrieved.
          content:
            application/json:
              schema:
                $ref: './all.yaml#/components/schemas/UserResource'
    put:
      tags:
        - Users
      operationId: updateUser
      summary: Update a user
      description: |
        Updates the user that matches the supplied id.
      requestBody:
        content:
          application/json:
            schema:
              $ref: './all.yaml#/components/schemas/UserResource'
      responses:
        '200':
          description: The user was successfully updated.
          content:
            application/json:
              schema:
                $ref: './all.yaml#/components/schemas/UserResource'
    delete:
      tags:
        - Users
      operationId: deleteUser
      summary: Delete a user
      description: |
        Deletes the user that matches the supplied id.
      responses:
        '200':
          description: The user was successfully deleted.
          content:
            application/json:
              schema: {}

info:
  title: Unity Catalog API
  version: '0.1'
